### ISSUE TITLE
Candidacy Confirmation

### ISSUE THREAD

**Issue by TiwariAbhishek23** [DiveHQ/backend-internship-task#18]
Hello, I applied for the octernship when it was first announced and noticed that only around 50 students had registered at that time. However, I encountered what I believed to be a glitch as the project did not appear in my task section on the octernship page. Today, I attempted to apply again and received a notification stating that the limit had been reached and applications were no longer being accepted. I assure you that I submitted my application on time and also completed the project as required.[](url)
<img width="978" alt="Screenshot 2023-06-14 at 9 10 46 PM" src="https://github.com/DiveHQ/backend-internship-task/assets/97469132/d0c30073-f6bb-48b6-9e38-8f2ee99158b4">

https://github.com/DiveHQ/backend-internship-task/assets/97469132/e64c5c19-0f04-4501-855e-e33309e6a8db

Could you kindly confirm if my candidacy for this position has been accepted? Thank you.

**Comment by prayashm** [comment]
I do see your submission and private repo in classroom.
Also please ask in Discussions.

**Comment by AbhishekTiwari23** [comment]
(Last Message)
Firstly, thanks for the confirmation. 
Regarding discussions, are you referring to GitHub Discussion or any Discord/Slack channels? If there are any groups specifically dedicated to this community, please let me as I have attempted to search for them but have yet to find any.
