### ISSUE TITLE
Can I get a new repo

### ISSUE THREAD

**Issue by TiwariAbhishek23** [DiveHQ/backend-internship-task#5]
Hello, my name is Abhishek. Currently, I am working on backend API project using fastApi. Unfortunately, I made a few errors during the process, and the biggest mistake I made was forgetting to add a gitignore file at the start of the project. As a result, I am now facing difficulties and would appreciate your assistance in starting the project again. Although I have almost completed it, I had used the rebase command, which has caused some issues.

**Comment by prayashm** [comment]
You should be able to start with a new branch for yourself.
